name: Muslim Islam AI Bot 24/7

on:
  schedule:
    - cron: "0 */6 * * *" # Har 6 ghante baad auto-restart
  workflow_dispatch: # Manual start button

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # Dependencies ko cache karega taake load fast ho

      - name: Install Dependencies
        run: |
          pip install python-telegram-bot==13.15 google-generativeai firebase-admin requests

      - name: Run Muslim Islam AI
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
        run: python bot.py
